#ifndef THEMESELECT_H
#define THEMESELECT_H

#include <QWidget>

class OptionsModel;

enum themes
{
	THEME_ALT_TEXT,

	// Autonomous Widgets

	THEME_BITCOINGUI,

	THEME_RPCCONSOLE,
	THEME_RPCCONSOLE_TAB,
	THEME_RPCCONSOLE_CONSOLE,
	THEME_RPCCONSOLE_BUTTON,
	THEME_RPCCONSOLE_SUBTITLE,
	THEME_RPCCONSOLE_LABEL,	

	THEME_WALLETFRAME,

	// Dialogs
	THEME_ABOUTDIALOG,

	THEME_ASKPASSPHRASEDIALOG,
	THEME_ASKPASSPHRASEDIALOG_BUTTON,

	THEME_EDITADDRESSDIALOG,
	THEME_MININGDIALOG,

	THEME_OPTIONSDIALOG,
	THEME_OPTIONSDIALOG_TAB,
	THEME_OPTIONSDIALOG_BUTTON,

	THEME_SIGNVERIFYDIALOG,
	THEME_SIGNVERIFYDIALOG_TAB,
	THEME_SIGNVERIFYDIALOG_BUTTON,

	THEME_TRANSACTIONDESCDIALOG,
	
	// Pages

	THEME_ADDRESSBOOKPAGE,
	THEME_ADDRESSBOOKPAGE_TABLE,
	THEME_ADDRESSBOOKPAGE_BUTTON_A,
	THEME_ADDRESSBOOKPAGE_BUTTON_B,
	
	THEME_OVERVIEWPAGE,
	
	THEME_RECEIVECOINSPAGE,
	THEME_RECEIVECOINSPAGE_TABLE,
	THEME_RECEIVECOINSPAGE_BUTTON_A,
	THEME_RECEIVECOINSPAGE_BUTTON_B,
	
	THEME_SENDCOINSPAGE,
	THEME_SENDCOINSPAGE_BUTTON,

	THEME_SENDCOINSENTRY,
	THEME_SENDCOINSENTRY_BUTTON,
	THEME_SENDCOINSENTRY_LINE,

	THEME_TRANSACTIONVIEW,
	THEME_TRANSACTIONVIEW_HEADER,

	ELEMENTS
};

void initStyle();

void setTheme();

void applyTheme(QWidget* target, int type);

void setOptionsModel(OptionsModel *optionsmodel);

#endif
